# Generated by Django 2.0.7 on 2018-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idcInfo',
            fields=[
                ('id', models.AutoField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('idcIp', models.CharField(max_length=32, unique=True, verbose_name='机房IP')),
                ('token', models.CharField(max_length=128, unique=True, verbose_name='token')),
                ('idcznName', models.CharField(max_length=32, unique=True, verbose_name='机房中文名称')),
                ('idcName', models.CharField(max_length=16, unique=True, verbose_name='机房英文名称')),
                ('webLoginInfo', models.CharField(max_length=128, unique=True, verbose_name='web登陆地址')),
                ('sshLoginInfo', models.CharField(max_length=128, unique=True, verbose_name='ssh登陆地址')),
                ('detail', models.TextField(max_length=256, verbose_name='描述')),
            ],
        ),
    ]
